# Use root/example as user/password credentials
version: '3.1'

services:

  database:
    image: mysql:5.6
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=nest"
    ports:
      - "33061:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: node_api
    command: >
      bash -c "yarn && node dist/main.js"
    volumes:
      - ..:/app
    ports:
      - '8080:8080'
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - database
    tty: true

  cache:
    image: redis:3.0
    ports:
      - "63791:6379"
    command: >
      --requirepass example
